var version,noSize,fullBulletin,originalUrl,searchTags=[],directDelivery,linked,bdiv,oiframe,display,displayUrl,bulletinRendered=!1,bulletinHeight=0,ua=navigator.userAgent||navigator.vendor,isIpad=0<=ua.indexOf("iPad;"),isApple=0<=ua.indexOf("iPhone;")||0<=ua.indexOf("iPad;")||0<=ua.indexOf("iPod;"),namePrefix="",bulletinPrefix="__BULLETIN__",bulletinForm=bulletinPrefix+"bulletinForm",bulletinDiv=bulletinPrefix+"bdiv",bulletinJS=!1,bulletinIncluded=!0;
function parseDbcli(a){var b={nf:!1,dup:!1,err:"",text:""};a||(a="");a=a.split("\n");for(var c=0;c<a.length;c++){var d=a[c],g=d.charAt(0);if(":"==g||"!"==g){for(g=1;g<d.length&&" "<d.charAt(g);)g++;var e=d.substring(1,g);if("NF"==e)b.nf=!0;else if("DUP"==e)b.dup=!0;else if("ERR"==e||"INT"==e){for(;g<d.length&&" ">=d.charAt(g);)g++;b.err&&(b.err+="\n");b.err+=d.substr(g)}}else 0<d.length&&(b.text&&(b.text+="\n"),b.text+=d)}return b}
function parseUrl(a){var b=[];a=a.split("&");for(var c=0,d=0;d<a.length;d++){var g=a[d].indexOf("="),e=[];0<=g?(e[0]=a[d].substr(0,g),e[1]=decodeURIComponent(a[d].substr(g+1).replace(/\+/g," "))):(e[0]=a[d],e[1]="");0<e[0].length&&(b[c++]=e)}return b}function getTag(){var a,b,c,d;1<arguments.length?(b=arguments[0],c=arguments[1]):(b=searchTags,c=arguments[0]);for(a=0;a<b.length&&(d=b[a],d[0]!=c);a++);return a<b.length?b[a][1]:null}
function loadXML(a,b,c,d,g){var e=new XMLHttpRequest;if(!e)return b&&b(e,a),400;d&&b&&(e.onreadystatechange=function(){4==e.readyState&&b(e,a)});c?e.open("GET",a,d?d:!1):(e.open("POST",a,d?d:!1),e.setRequestHeader("Content-Type","application/x-www-form-urlencoded"));e.send(g);!d&&b&&b(e,a);return e.status}function buildCGI(a){for(var b=webServer+cgiFilesDir+cgiCmdPrefix+a,c=cgiCmdSuffix,d=1;d<arguments.length;d++)arguments[d]&&0<arguments[d].length&&(b+=c+arguments[d],c="&");return b}
function originalTags(a,b){for(var c="",d="",g=!1,e=0;e<searchTags.length;e++){var f=searchTags[e];f[0]!=originalTag&&(c+=d+f[0]+(f[1]?"="+encodeURIComponent(f[1]):""),d="&",g||f[0]!=linkedTag||(g=!0))}b&&!g&&(c+=d+linkedTag,d="&");null!=a&&(c+=d+originalTag+(a.length?"="+encodeURIComponent(a):""));return c}function setLocation(a,b,c){c||display?a.location.href=b:a.location.replace(buildCGI(redirectCGI,originalTag+"="+encodeURIComponent(b)))}
function noBulletin(a){display?(alert("Bulletin cannot render: "+(a?a:"reason unknown")),bulletinJS||setLocation(self,originalUrl,!1)):notifyBailout?(a=buildCGI(redirectCGI,0<=renderDelay&&1<notifyBailoutActionRender?statusTag+"="+(notifyBailoutActionRender-1):"",0>renderDelay&&1<notifyBailoutActionNonRender?resetTag+"=true":"",a?reasonTag+"="+encodeURIComponent(a):"",reasonPassUp?passTag+"=true":"",originalTags(bulletinJS?noOriginalValue:originalUrl)),bulletinJS?(new Image).src=a:self.location.replace(a)):
bulletinJS||(directDelivery?self.location.reload(!0):setLocation(self,originalUrl,!1))}function isUri(a){return/^[a-z][a-z0-9+.\-]*:/i.test(a)}function isHttp(a){return"http://"==a.substr(0,7).toLowerCase()||"https://"==a.substr(0,8).toLowerCase()}function webPath(a,b){isHttp(a)||("/"==a.charAt(0)||!builtinServer&&b||!webFilesDir||(a=webFilesDir+a),webServer&&(b&&(a=(builtinServer?"/"+dynCGI:cgiFilesDir+cgiCmdName+"?"+commandTag+"="+dynCGI+"&"+nameTag+"=")+a),a=webServer+a));return a}
var isMobileResult=-1;function isMobile(){-1==isMobileResult&&(isMobileResult=0<=ua.indexOf("Mobi")&&!isIpad);return isMobileResult}function setCSS(a,b){a=webPath(a,b);if(document.createStyleSheet)document.createStyleSheet(a,0);else{var c=document.createElement("link");c.rel="stylesheet";c.type="text/css";c.href=a;document.getElementsByTagName("head")[0].appendChild(c)}}function setBulletinHeight(){bulletinHeight=""!=bdiv.style.zIndex?0:bdiv.offsetHeight+bdiv.offsetTop}
function getWinHeight(){var a=480;"number"==typeof self.innerHeight?a=self.innerHeight:document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?a=document.documentElement.clientHeight:document.body&&(document.body.clientWidth||document.body.clientHeight)&&(a=document.body.clientHeight);return a}
function getWinWidth(){var a=640;"number"==typeof self.innerWidth?a=self.innerWidth:document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?a=document.documentElement.clientWidth:document.body&&(document.body.clientWidth||document.body.clientHeight)&&(a=document.body.clientWidth);return a}
function resizeIFrame(){if(oiframe)if(-1==bulletinHeight)oiframe.height=getWinHeight();else{setBulletinHeight();var a=getWinHeight()-bulletinHeight;isMobile()?oiframe.height=getWinHeight():oiframe.height=0>a?200:a}}function orientationChange(){var a=bdiv.style.display;bdiv.style.display="none";bdiv.style.display=a;setTimeout(resizeIFrame,200)}function sendRenderBulletin(){0<=renderDelay&&(renderDelay=-1,(new Image).src=buildCGI(notifyCGI,statusTag+"=0",originalTags(null)))}
function renderBulletin(){if(!bulletinRendered){bulletinRendered=!0;bdiv.style.visibility="visible";0==renderDelay?sendRenderBulletin():0<renderDelay&&setTimeout(sendRenderBulletin,renderDelay);var a=document.createElement("style");a.type="text/css";a.styleSheet?a.styleSheet.cssText="* { max-height: 1000000px; }":a.appendChild(document.createTextNode("* { max-height: 1000000px; }"));document.getElementsByTagName("head")[0].appendChild(a);noSize||fullBulletin||resizeIFrame();"function"==typeof afterRender&&
afterRender()}}function getUrlOf(a){var b=null;if(a)try{b=a.contentWindow.location.href}catch(c){a.src&&(b=a.src)}return b}var lastTitle=null,iframeLoading=0;
function iframeLoad(){if(iframeLoading){var a=oiframe?getUrlOf(oiframe):null;if(bailoutCrossDomain&&0<=renderDelay){if(!a&&!display)return noBulletin("cross-domain");0<bailoutCrossDomain&&bailoutCrossDomain--}1==iframeLoading&&(iframeLoading=2,0!=bulletinDelay&&renderBulletin());if(oiframe){var b=null;try{b=oiframe.contentDocument?oiframe.contentDocument.title:oiframe.Document.title}catch(c){b=null}b&&b!=lastTitle&&(document.title=lastTitle=b);a&&(originalUrl=a)}"function"==typeof afterIframeLoad&&
afterIframeLoad()}}
function load(){if(bailoutOpener&&self.opener)return noBulletin("In pop-up");document.body.rightMargin=0;document.body.leftMargin=0;document.body.bottomMargin=0;bdiv=document.getElementById("bdiv");oiframe=document.getElementById("oiframe");noSize||fullBulletin||(self.onresize=resizeIFrame,addListener(self,"orientationchange",orientationChange));if(bdiv){if(0<fullMinHeight&&getWinHeight()<fullMinHeight)return noBulletin("Full window too small ("+getWinHeight()+"<"+fullMinHeight+")");if(isMobile()){var a=
document.createElement("meta");a.name="viewport";a.content="width=device-width, initial-scale=1.0";document.getElementsByTagName("head")[0].appendChild(a)}if(!fullBulletin&&(document.body.scroll="no",noSize||setBulletinHeight(),oiframe)){oiframe.hspace=0;oiframe.vspace=0;if(!noSize){a=getWinHeight()-bulletinHeight;if(!isMobile()&&0<iframeMinHeight&&a<iframeMinHeight)return noBulletin("Window too small");isMobile()?oiframe.height=getWinHeight():oiframe.height=0>a?200:a}iframeLoading=1;setLocation(oiframe.contentWindow,
originalUrl,!1)}isMobile()||fullBulletin||(document.body.style.overflow="hidden");0==bulletinDelay||fullBulletin?renderBulletin():0<bulletinDelay&&setTimeout(renderBulletin,bulletinDelay);"function"==typeof afterLoad&&afterLoad();return!0}setLocation(top,originalUrl,!1)}function getDisplayUrl(){return webPath(displayUrl)}
function bulletinSetup(a){searchTags=parseUrl(a);"node"==getTag(displayTag)?display=2:display||null==getTag(displayTag)||(display=1);if(!linked&&null!=getTag(linkedTag)){linked=!0;a=self.location.pathname;var b=a.lastIndexOf("/");0<=b&&"/index.html"==a.substr(b)&&(a=a.substr(0,b),b=a.lastIndexOf("/"),0<=b&&(namePrefix=a.substr(b+1)+": "))}display||linked||directDelivery||null!=getTag(policyTag)||(display=1);originalUrl=getTag(originalTag);null==originalUrl&&(directDelivery?originalUrl=display?getDisplayUrl():
self.location.href:linked?fullBulletin=!0:originalUrl=getDisplayUrl());bulletinJS||version||(version=getTag(versionTag),version&&!isNan(parseInt(version)))||(version=2);if("false"==getTag(renderTag)||linked||display)renderDelay=-1}function bulletinInit(a){directDelivery=!1;renderDelay=-1;a||(a=self.location.search.substring(1));bulletinSetup(a)}
function nesting(a){(directDelivery="<$bt>"!=a)||(a=self.location.search.substring(1));bulletinSetup(a);if(!(1<display)){if(isApple&&0>ua.indexOf("Safari"))return noBulletin("iOS app");a=!1;try{parent!=self&&(a=!0)}catch(b){a=!0}a?noBulletin("Nested"):self.onload=load;return a}}
function dragOBJ(a,b){var c,d,g,e,f;Math.max(ua.toLowerCase().indexOf("msie"),0)?(c=event.clientX,d=event.clientY):(c=b.clientX,d=b.clientY);g=parseInt(a.style.right);e=parseInt(a.style.bottom);oiframe.style.visibility="hidden";document.onmousemove=function(b){if(!f){var h;Math.max(ua.toLowerCase().indexOf("msie"),0)?(h=event.clientX,b=event.clientY):(h=b.clientX,b=b.clientY);a.style.right=g+c-h+"px";a.style.bottom=e+d-b+"px"}};document.onmouseup=function(){f=1;document.onmousemove=null;document.onmouseup=
null;document.onselectstart=null;oiframe.style.visibility="visible"};document.body.focus();document.onselectstart=function(){return!1};return!1}function loadInParent(){var a=getUrlOf(oiframe);a&&1<iframeLoading&&originalUrl!=a?setLocation(parent,a,!1):display?setLocation(parent,originalUrl,!1):parent.location.reload(!0)}function maximizeIFrame(){bdiv.style.display="none";bulletinRendered=!0;oiframe.height=getWinHeight();bulletinHeight=-1}
function closeBulletin(){if(1<display)alert("Close does not function in preview");else if(bulletinJS)bdiv.parentNode.removeChild(bdiv);else if(bdiv&&!fullBulletin&&directDelivery)switch(closeMode){case 1:loadInParent();break;case 2:maximizeIFrame()}else directDelivery&&!display?self.location.reload(!0):originalUrl?setLocation(top,originalUrl,!1):(self.open(location,"_self").close(),self.close())}
function findFormTag(a,b){for(var c=0;c<a.elements.length;c++){var d=a.elements[c];if(d.name==b)return d}return null}function displayFormTags(a){for(var b="",c=0;c<a.elements.length;c++)var d=a.elements[c],b=b+(", "+d.name+" = "+d.value);return b}function addFormTag(a,b,c){var d=findFormTag(a,b);d||(d=document.createElement("input"),d.type="hidden",d.name=b,a.appendChild(d));d.value=c?c:""}function buttonOk(){return display?(alert("Button does not function in preview"),!1):!0}
function getButtonName(a){namePrefix.substr(0,nameTag.length+1)==nameTag+"="&&(namePrefix=decodeURIComponent(namePrefix.substr(nameTag.length+1)));return namePrefix+a}
function doCgi(a,b,c){if(buttonOk()){sendRenderBulletin();c=createForm(c);a.substr(0,webServer.length)==webServer&&(a=a.substr(webServer.length));a.substr(0,cgiFilesDir.length)==cgiFilesDir&&(a=a.substr(cgiFilesDir.length));var d=a.indexOf("?");if(0<=d){var g=a.substr(d+1);a=a.substr(0,d);g=parseUrl(g);for(d=0;d<g.length;d++){var e=g[d];e[0]!=commandTag&&e[0]!=buttonTag&&"web"!=e[0]&&addFormTag(c,e[0],e[1])}}addFormTag(c,commandTag,a);b&&addFormTag(c,buttonTag,getButtonName(b));addFormTag(c,"web",
webFilesDir);c.action=buildCGI((b?buttonPrefix:"")+a);c.submit();c.target&&setTimeout(closeBulletin,100);return!1}}function sendButton(a,b){!display&&a&&(sendRenderBulletin(),(new Image).src=buildCGI(buttonCGI,nameTag+"="+encodeURIComponent(getButtonName(a)),originalTags(noOriginalValue)));b&&setTimeout(b,100)}function doClose(a){sendButton(a,closeBulletin);return!1}function doNav(a,b){sendButton(b,function(){setLocation(self,a,!0)});return!1}
function doPrint(a){sendButton(a,self.print);return!1}function doButton(a,b,c){sendButton(a);b(c);return!1}function buttonEvent(a,b,c){null!=a&&setTimeout("self.status = '"+a+"';",0);b&&c&&document.images&&document.images[b]&&document.images[b].src!=c&&(document.images[b].src=c);return!0}var buttonImgClass="";function setButtonClass(a){buttonImgClass=a?' class="'+a+'"':""}var buttonNum=0,html,buttons=[];
function createForm(a){var b=document.createElement("div");b.setAttribute("style","display:none;");b.style.display="none";var c=document.createElement("form");c.id=bulletinForm;c.action="";c.method="post";a||c.setAttribute("target","_blank");for(i=0;i<searchTags.length;i++){var d=searchTags[i];d[0]!=originalTag&&d[0]!=buttonTag&&addFormTag(c,d[0],d[1].replace(/"/g,'\\"'))}a&&originalUrl&&addFormTag(c,originalTag,originalUrl.replace(/"/g,'\\"'));b.appendChild(c);document.getElementsByTagName("body")[0].appendChild(b);
return c}
function makeButton(a,b,c,d,g,e){var f="",l="button"+buttonNum++,h=bulletinPrefix+l,m=!1,q=!1;"!"==c.charAt(0)?(m=!0,c=c.substring(1)):"~"==c.charAt(0)&&(q=!0,c=c.substring(1));if(d||e){var n,k;"!"==d.charAt(0)?n=d.substr(1):(k=d.split(",",2),d=webPath(k[0]),1<k.length?(k=webPath(k[1]),(new Image).src=k):k=d);f=(e?f+"<area":f+"<a")+(' id="'+h+'"');if("Nav"==b){var p;"javascript:"==c.substr(0,11).toLowerCase()&&(p=m=!0,c=c.substr(11).replace(/"/g,'\\"'));b=p?"#":isUri(c)?c:webPath(c)+"?"+originalTags(m?
originalUrl:null,!0);f+=' href="'+(display||p?b:buildCGI(buttonCGI,nameTag+"="+encodeURIComponent(getButtonName(a)),originalTags(b)))+'"'+(m?"":' target="_blank"');bulletinJS?p&&"function"==typeof doJavaScript?buttons.push(new button(h,"click",doJavaScript,c,a)):q&&buttons.push(new button(h,"click",doClose)):p?f+=' onclick="'+c+'"':q&&(f+=' onclick="doClose(); return true;"')}else"Cgi"==b?(f+=' href="#"',bulletinJS?buttons.push(new button(h,"click",doCgi,c,a,m)):f+=" onclick=\"return doCgi('"+c+"', '"+
a+"', "+m+');"'):"Close"==b?(f+=' href="#"',bulletinJS?buttons.push(new button(h,"click",doClose,a)):f+=" onclick=\"return doClose('"+a+"');\""):"Print"==b?(f+=' href="#"',bulletinJS?buttons.push(new button(h,"click",doPrint,a)):f+=" onclick=\"return doPrint('"+a+"');\""):(f+=' href="#"',bulletinJS?buttons.push(new button(h,"click",doClose,a)):f+=' onclick="return do'+b+"('"+c+"', '"+a+"');\"");bulletinJS?n?(buttons.push(new button(h,"mouseover",buttonEvent,a,"")),buttons.push(new button(h,"mouseout",
buttonEvent,""))):(buttons.push(new button(h,"mouseover",buttonEvent,a,l,k)),buttons.push(new button(h,"mouseout",buttonEvent,l,d))):f=f+(" onmouseover=\"return buttonEvent('"+a+"'"+(n?"":", '"+l+"', '"+k+"'")+');"')+(" onmouseout=\"return buttonEvent(''"+(n?"":", '"+l+"', '"+d+"'")+');"');e&&(f+=' coords="'+e+'"');g&&(f+=' shape="'+g+'"');d&&!e&&(f=n?f+(">"+n+"</a"):f+('><img id="'+h+'i" name="'+l+'"'+buttonImgClass+' src="'+d+'" border=0></a'));f+=">"}else f+='<form action="#" method="get"',"Nav"==
b&&originalUrl&&(f+=' target="_blank"'),f+='><input type="button" value="'+a+'"',f+=' onclick="return do'+b+"('"+c+"', '"+a+"');\" border=0></form>";html?html+=f:document.write(f)}function bulletinOpen(a){bulletinJS?html="":document.open()}function bulletinWrite(a){bulletinJS?html+=a:document.writeln(a)}function bulletinClose(){bulletinJS?bdivAdd(html):document.close()}
function button(a,b,c){this.id=a;this.type=b;this.func=c;this.params=[];for(var d=3;d<arguments.length;d++)this.params[d-3]=arguments[d]}
function addButtonEvents(){for(i=0;i<buttons.length;i++){var a=document.getElementById(buttons[i].id);a&&addListener(a,buttons[i].type,function(a){var b;a.currentTarget?b=a.currentTarget.id:(b=a.srcElement.id,b||(b=a.srcElement.parentElement.id));if(b)for(i=0;i<buttons.length;i++)if(buttons[i].type==a.type&&buttons[i].id==b){buttons[i].func.apply(null,buttons[i].params);break}})}}
function addListener(a,b,c){a.addEventListener?a.addEventListener(b,c,!0):a.attachEvent?a.attachEvent("on"+b,c):a["on"+b]=c}function removeListener(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!0):a.detachEvent?a.detachEvent("on"+b,c):a["on"+b]=null}var bdivLeft,bdivTop,bdivBottom,bdivRight,bdivStyleNo=1,bdivStyleFixed=2,bdivStyle="absolute",checkImageCount=12;
function checkImageComplete(){for(var a=0,b=bdiv.getElementsByTagName("img"),c=0;c<b.length;c++)b[c].complete&&a++;c!=a&&0<checkImageCount--?setTimeout(checkImageComplete,250):2>display&&(getWinHeight()<bdiv.offsetHeight||getWinWidth()<bdiv.offsetWidth)?(noBulletin("Window too small"),closeBulletin()):(bdivMove(),addButtonEvents(),renderBulletin())}function bdivSetAbsoulte(){bdivStyle="absolute";bdiv.style.position=bdivStyle}
function bdivAdd(a){bdiv=document.createElement("div");bdiv.setAttribute("id",bulletinDiv);bdivStyle&&(bdiv.setAttribute("style","position:"+bdivStyle+"; z-index:999999999; visibility:hidden;"),bdiv.style.position=bdivStyle,"undefined"!=typeof bdivBottom&&(bdivTop=0),bdiv.style.top=bdivTop+"px","undefined"!=typeof bdivLeft&&(bdiv.style.left=bdivLeft+"px"),"undefined"!=typeof bdivRight&&(bdiv.style.right=bdivRight+"px"),bdiv.style.zIndex="999999999",bdiv.style.visibility="hidden");bdiv.innerHTML=a;
a=document.getElementsByTagName("body")[0];a.insertBefore(bdiv,a.firstChild);addListener(self,"scroll",bdivMove);addListener(self,"resize",bdivMove);checkImageComplete();1==display&&setLocation(document.getElementById("oiframe").contentWindow,originalUrl,!1)}function bdivMove(){if(bdivStyle){var a=document.documentElement&&document.documentElement.scrollTop||document.body.scrollTop;bdiv.style.top="undefined"!=typeof bdivBottom?getWinHeight()-bdiv.offsetHeight-bdivBottom+a+"px":bdivTop+a+"px"}}
function loadImage(){bdivMove()}function checkForBody(){document.getElementById(bulletinDiv)||document.getElementById("bdiv")?noBulletin("Nested"):null==document.getElementsByTagName("body")[0]?setTimeout(checkForBody,1E3):display||parent==self?(Bulletin(),"function"==typeof afterLoad&&afterLoad()):noBulletin("Window not parent")}
function jsBulletin(a,b){b&&(bdivStyle=b==bdivStyleFixed?"fixed":null);bulletinJS=!0;var c=a.split(" "),d=1<c.length?c[1].indexOf("?"):-1,c=-1==d?"":c[1].substr(d+1);-1!=(d=c.indexOf("cmd=dyn&name="))&&(c=-1!=(d=c.indexOf("&",d+13))?c.substring(d+1):"");(directDelivery=""!=c)||(c=self.location.search.substring(1));bulletinSetup(c);directDelivery&&(webServer=getTag(webServerTag));setTimeout(checkForBody,display?100:2E3);display||document.writeln('<script type="text/javascript" src="'+buildCGI(redirectCGI,
originalTag+"="+encodeURIComponent(originalUrl))+'">\x3c/script>')};
